name: gdestiny_server
author: P.Y. Laligand
version: 0.0.1
description: A server supporting the gdestiny.com website.
dependencies:
  bungie_client:
    git:
      url: https://github.com/pylaligand/dart-bungie-client.git
  logging: ^0.11.2
  postgresql: ^0.3.3
  shelf: ^0.6.5
  shelf_route: ^0.14.1
